version: '3'
services:
  python:
    build: .
    volumes:
      - ".:/fanxing"
    environment:
      - "DEBUG=0"
    restart: always
    expose:
      - "8000"
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  nginx:
    restart: always
    image: "nginx"
    ports:
      - "8080:80"
      - "8081:81"
    volumes:
      - "./nginxtemplates:/etc/nginx/templates"
      - ".:/fanxing"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"