# Generated by Django 4.0.3 on 2022-03-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_tolongtryflag_profile_tulong_endtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tolongtryflag',
            new_name='tulongtryflag',
        ),
    ]
