# Generated by Django 4.0.3 on 2022-03-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_tolongtryflag_profile_tulongtryflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tulong_accout_numlimit',
            field=models.IntegerField(default=5, verbose_name='账号数量'),
        ),
    ]
